language: python
python: 3.5
branches:
  only:
  - build


before_install:
  - openssl aes-256-cbc -K $encrypted_2e4e0a4dcd28_key -iv $encrypted_2e4e0a4dcd28_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "lovew"
  - git config --global user.email "love@google.com"
  - git clone git@github.com:lovew/hello.git
  - cd hello

install:
  - echo '123123' >> test.txt
  - git add test.txt
  - git commit -m "test1"
  - git push -u origin master